apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 30566
  type: LoadBalancer
  loadBalancerIP: 10.1.1.160
